version: '2'
services:
  web:
    build: .
    command: python runtests.py
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres1:5432/postgres
      - SHARD_001_DATABASE_URL=mysql://mysqlu:mysqlpw:@mysql:3306/mysqldb
      - SHARD_002_DATABASE_URL=postgres://postgres:postgres@postgres2:5432/postgres
      - SHARD_003_DATABASE_URL=postgres://postgres:postgres@postgres3:5432/postgres
      - SHARD_004_DATABASE_URL=postgres://postgres:postgres@postgres4:5432/postgres
      - REPLICA_001_DATABASE_URL=postgres://postgres:postgres@postgres5:5432/postgres
      - REPLICA_002_DATABASE_URL=postgres://postgres:postgres@postgres6:5432/postgres
    depends_on:
      - mysql
      - postgres1
      - postgres2
      - postgres3
      - postgres4
      - postgres5
      - postgres6

  postgres1:
    image: convox/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  postgres2:
    image: convox/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  postgres3:
    image: convox/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  postgres4:
    image: convox/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  postgres5:
    image: convox/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  postgres6:
    image: convox/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  mysql:
    image: convox/mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqlu
      MYSQL_PASSWORD: mysqlpw
